// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: dm.proto

package dm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DmSegMobileReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 弹幕列表
	Elems []*DanmakuElem `protobuf:"bytes,1,rep,name=elems,proto3" json:"elems,omitempty"`
	// 是否已关闭弹幕
	// 0:未关闭 1:已关闭
	State int32 `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	// 弹幕云屏蔽ai评分值
	AiFlag *DanmakuAIFlag `protobuf:"bytes,3,opt,name=ai_flag,json=aiFlag,proto3" json:"ai_flag,omitempty"`
}

func (x *DmSegMobileReply) Reset() {
	*x = DmSegMobileReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DmSegMobileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DmSegMobileReply) ProtoMessage() {}

func (x *DmSegMobileReply) ProtoReflect() protoreflect.Message {
	mi := &file_dm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DmSegMobileReply.ProtoReflect.Descriptor instead.
func (*DmSegMobileReply) Descriptor() ([]byte, []int) {
	return file_dm_proto_rawDescGZIP(), []int{0}
}

func (x *DmSegMobileReply) GetElems() []*DanmakuElem {
	if x != nil {
		return x.Elems
	}
	return nil
}

func (x *DmSegMobileReply) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *DmSegMobileReply) GetAiFlag() *DanmakuAIFlag {
	if x != nil {
		return x.AiFlag
	}
	return nil
}

// 弹幕ai云屏蔽列表
type DanmakuAIFlag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 弹幕ai云屏蔽条目
	DmFlags []*DanmakuFlag `protobuf:"bytes,1,rep,name=dm_flags,json=dmFlags,proto3" json:"dm_flags,omitempty"`
}

func (x *DanmakuAIFlag) Reset() {
	*x = DanmakuAIFlag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DanmakuAIFlag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanmakuAIFlag) ProtoMessage() {}

func (x *DanmakuAIFlag) ProtoReflect() protoreflect.Message {
	mi := &file_dm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanmakuAIFlag.ProtoReflect.Descriptor instead.
func (*DanmakuAIFlag) Descriptor() ([]byte, []int) {
	return file_dm_proto_rawDescGZIP(), []int{1}
}

func (x *DanmakuAIFlag) GetDmFlags() []*DanmakuFlag {
	if x != nil {
		return x.DmFlags
	}
	return nil
}

// 弹幕ai云屏蔽条目
type DanmakuFlag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 弹幕dmid
	Dmid int64 `protobuf:"varint,1,opt,name=dmid,proto3" json:"dmid,omitempty"`
	// 评分
	Flag uint32 `protobuf:"varint,2,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *DanmakuFlag) Reset() {
	*x = DanmakuFlag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DanmakuFlag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanmakuFlag) ProtoMessage() {}

func (x *DanmakuFlag) ProtoReflect() protoreflect.Message {
	mi := &file_dm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanmakuFlag.ProtoReflect.Descriptor instead.
func (*DanmakuFlag) Descriptor() ([]byte, []int) {
	return file_dm_proto_rawDescGZIP(), []int{2}
}

func (x *DanmakuFlag) GetDmid() int64 {
	if x != nil {
		return x.Dmid
	}
	return 0
}

func (x *DanmakuFlag) GetFlag() uint32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

// 弹幕条目
type DanmakuElem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 弹幕dmid
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 弹幕出现位置(单位ms)
	Progress int32 `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	// 弹幕类型
	Mode int32 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	// 弹幕字号
	Fontsize int32 `protobuf:"varint,4,opt,name=fontsize,proto3" json:"fontsize,omitempty"`
	// 弹幕颜色
	Color uint32 `protobuf:"varint,5,opt,name=color,proto3" json:"color,omitempty"`
	// 发送着mid hash
	MidHash string `protobuf:"bytes,6,opt,name=midHash,proto3" json:"midHash,omitempty"`
	// 弹幕正文
	Content string `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	// 发送时间
	Ctime int64 `protobuf:"varint,8,opt,name=ctime,proto3" json:"ctime,omitempty"`
	// 权重 区间:[1,10]
	Weight int32 `protobuf:"varint,9,opt,name=weight,proto3" json:"weight,omitempty"`
	// 动作
	Action string `protobuf:"bytes,10,opt,name=action,proto3" json:"action,omitempty"`
	// 弹幕池
	Pool int32 `protobuf:"varint,11,opt,name=pool,proto3" json:"pool,omitempty"`
	// 弹幕dmid str
	IdStr string `protobuf:"bytes,12,opt,name=idStr,proto3" json:"idStr,omitempty"`
	// 弹幕属性位(bin求AND)
	// bit0:保护 bit1:直播 bit2:高赞
	Attr int32 `protobuf:"varint,13,opt,name=attr,proto3" json:"attr,omitempty"`
}

func (x *DanmakuElem) Reset() {
	*x = DanmakuElem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DanmakuElem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanmakuElem) ProtoMessage() {}

func (x *DanmakuElem) ProtoReflect() protoreflect.Message {
	mi := &file_dm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanmakuElem.ProtoReflect.Descriptor instead.
func (*DanmakuElem) Descriptor() ([]byte, []int) {
	return file_dm_proto_rawDescGZIP(), []int{3}
}

func (x *DanmakuElem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DanmakuElem) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *DanmakuElem) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *DanmakuElem) GetFontsize() int32 {
	if x != nil {
		return x.Fontsize
	}
	return 0
}

func (x *DanmakuElem) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *DanmakuElem) GetMidHash() string {
	if x != nil {
		return x.MidHash
	}
	return ""
}

func (x *DanmakuElem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DanmakuElem) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *DanmakuElem) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *DanmakuElem) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DanmakuElem) GetPool() int32 {
	if x != nil {
		return x.Pool
	}
	return 0
}

func (x *DanmakuElem) GetIdStr() string {
	if x != nil {
		return x.IdStr
	}
	return ""
}

func (x *DanmakuElem) GetAttr() int32 {
	if x != nil {
		return x.Attr
	}
	return 0
}

var File_dm_proto protoreflect.FileDescriptor

var file_dm_proto_rawDesc = []byte{
	0x0a, 0x08, 0x64, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x64, 0x61, 0x6e, 0x6d,
	0x61, 0x6b, 0x75, 0x22, 0x85, 0x01, 0x0a, 0x10, 0x44, 0x6d, 0x53, 0x65, 0x67, 0x4d, 0x6f, 0x62,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x65, 0x6c, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x61, 0x6e, 0x6d, 0x61, 0x6b,
	0x75, 0x2e, 0x44, 0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x45, 0x6c, 0x65, 0x6d, 0x52, 0x05, 0x65,
	0x6c, 0x65, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2f, 0x0a, 0x07, 0x61, 0x69,
	0x5f, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x61,
	0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x2e, 0x44, 0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x41, 0x49, 0x46,
	0x6c, 0x61, 0x67, 0x52, 0x06, 0x61, 0x69, 0x46, 0x6c, 0x61, 0x67, 0x22, 0x40, 0x0a, 0x0d, 0x44,
	0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x41, 0x49, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x2f, 0x0a, 0x08,
	0x64, 0x6d, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x64, 0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x2e, 0x44, 0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75,
	0x46, 0x6c, 0x61, 0x67, 0x52, 0x07, 0x64, 0x6d, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x22, 0x35, 0x0a,
	0x0b, 0x44, 0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x64, 0x6d, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x66, 0x6c, 0x61, 0x67, 0x22, 0xb7, 0x02, 0x0a, 0x0b, 0x44, 0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75,
	0x45, 0x6c, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x6d, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6f, 0x6e, 0x74, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x66, 0x6f, 0x6e, 0x74, 0x73, 0x69, 0x7a, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x69, 0x64, 0x48, 0x61, 0x73,
	0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x69, 0x64, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6f, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x70, 0x6f, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x64, 0x53, 0x74, 0x72, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x64, 0x53, 0x74, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x74,
	0x74, 0x72, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x61, 0x74, 0x74, 0x72, 0x42, 0x05,
	0x5a, 0x03, 0x2f, 0x64, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dm_proto_rawDescOnce sync.Once
	file_dm_proto_rawDescData = file_dm_proto_rawDesc
)

func file_dm_proto_rawDescGZIP() []byte {
	file_dm_proto_rawDescOnce.Do(func() {
		file_dm_proto_rawDescData = protoimpl.X.CompressGZIP(file_dm_proto_rawDescData)
	})
	return file_dm_proto_rawDescData
}

var file_dm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dm_proto_goTypes = []interface{}{
	(*DmSegMobileReply)(nil), // 0: danmaku.DmSegMobileReply
	(*DanmakuAIFlag)(nil),    // 1: danmaku.DanmakuAIFlag
	(*DanmakuFlag)(nil),      // 2: danmaku.DanmakuFlag
	(*DanmakuElem)(nil),      // 3: danmaku.DanmakuElem
}
var file_dm_proto_depIdxs = []int32{
	3, // 0: danmaku.DmSegMobileReply.elems:type_name -> danmaku.DanmakuElem
	1, // 1: danmaku.DmSegMobileReply.ai_flag:type_name -> danmaku.DanmakuAIFlag
	2, // 2: danmaku.DanmakuAIFlag.dm_flags:type_name -> danmaku.DanmakuFlag
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_dm_proto_init() }
func file_dm_proto_init() {
	if File_dm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DmSegMobileReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DanmakuAIFlag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DanmakuFlag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DanmakuElem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dm_proto_goTypes,
		DependencyIndexes: file_dm_proto_depIdxs,
		MessageInfos:      file_dm_proto_msgTypes,
	}.Build()
	File_dm_proto = out.File
	file_dm_proto_rawDesc = nil
	file_dm_proto_goTypes = nil
	file_dm_proto_depIdxs = nil
}
